GRAPH_PATH = "/data/graphs/bin/"
#GRAPH_PATH = "/home/csgrads/xjian140/Counter3/testcases/bin/"
graphs = [
    "sd_arc_sym",
    "friendster_sym",
    "twitter_sym",
    "arabic_sym",
    "planet_sym",
    "uk-2002_sym",
    "eu-2015-host_sym",
    "europe_sym",
    "indochina_sym",
    "enwiki-2023_sym",
    "asia_sym",
    "com-orkut_sym",
    "north-america_sym",
    "us_sym",
    "socfb-konect_sym",
    "socfb-uci-uni_sym",
    "hollywood_2009_sym",
    "africa_sym",
    "soc-LiveJournal1_sym",
    "hugebubbles-00020_sym",
    "RoadUSA_sym",
    "hugetrace-00020_sym",
    "Germany_sym",
    "in_2004_sym",
    "skitter_sym",
    "WikiTalk_sym",
    "web-Google_sym",
    "com-youtube_sym",
    "roadNet-CA_sym",
    "DBLP_sym",
    "NotreDame_sym",
    "Slashdot_sym",
    "Epinions1_sym",
    "HepPh_sym"
]